// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(FoodiePalContext))]
    partial class FoodiePalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Cuisin", b =>
                {
                    b.Property<string>("CuiName")
                        .HasColumnName("cui_name")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Descript")
                        .HasColumnName("descript")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.HasKey("CuiName");

                    b.ToTable("cuisin");
                });

            modelBuilder.Entity("WebApplication1.Models.Resturant", b =>
                {
                    b.Property<int>("RestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("rest_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phone_number")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("RestAddress")
                        .HasColumnName("rest_address")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("RestName")
                        .HasColumnName("rest_name")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.HasKey("RestId");

                    b.ToTable("resturant");
                });

            modelBuilder.Entity("WebApplication1.Models.ResturantCuisin", b =>
                {
                    b.Property<int>("RestId")
                        .HasColumnName("rest_id");

                    b.Property<string>("CuiName")
                        .HasColumnName("cui_name")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.HasKey("RestId", "CuiName");

                    b.HasIndex("CuiName");

                    b.ToTable("resturant_cuisin");
                });

            modelBuilder.Entity("WebApplication1.Models.ResturantCuisin", b =>
                {
                    b.HasOne("WebApplication1.Models.Cuisin", "CuiNameNavigation")
                        .WithMany("ResturantCuisin")
                        .HasForeignKey("CuiName")
                        .HasConstraintName("FK__resturant__cui_n__534D60F1");

                    b.HasOne("WebApplication1.Models.Resturant", "Rest")
                        .WithMany("ResturantCuisin")
                        .HasForeignKey("RestId")
                        .HasConstraintName("FK__resturant__rest___52593CB8");
                });
#pragma warning restore 612, 618
        }
    }
}
