// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(FoodiePalContext))]
    partial class FoodiePalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("WebApplication1.Models.Cuisin", b =>
                {
                    b.Property<string>("CuiName")
                        .HasColumnName("cui_name")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Descript")
                        .HasColumnName("descript")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.HasKey("CuiName");

                    b.ToTable("cuisin");

                    b.HasData(
                        new { CuiName = "Chinese" },
                        new { CuiName = "Korean" },
                        new { CuiName = "Canadian" },
                        new { CuiName = "Malaysian" }
                    );
                });

            modelBuilder.Entity("WebApplication1.Models.Resturant", b =>
                {
                    b.Property<int>("RestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("rest_id");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("PhoneNumber")
                        .HasColumnName("phone_number")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("RestAddress")
                        .HasColumnName("rest_address")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("RestName")
                        .HasColumnName("rest_name")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.HasKey("RestId");

                    b.ToTable("resturant");

                    b.HasData(
                        new { RestId = 1, Email = "peaceful@resturant", PhoneNumber = "222-454-5345", RestAddress = "2222 Seymour Street", RestName = "Peaceful Resturant" },
                        new { RestId = 2, Email = "peaceful@resturant", PhoneNumber = "222-454-5345", RestAddress = "2222 Robson Street", RestName = "Sura" },
                        new { RestId = 3, Email = "peaceful@resturant", PhoneNumber = "222-454-5345", RestAddress = "2222 Richards Street", RestName = "A&W" },
                        new { RestId = 4, Email = "peaceful@resturant", PhoneNumber = "222-454-5345", RestAddress = "2222 Homer Street", RestName = "Banana Republic" },
                        new { RestId = 5, Email = "peaceful@resturant", PhoneNumber = "222-454-5345", RestAddress = "2222 Howe Street", RestName = "Dynasty" }
                    );
                });

            modelBuilder.Entity("WebApplication1.Models.ResturantCuisin", b =>
                {
                    b.Property<int>("RestId")
                        .HasColumnName("rest_id");

                    b.Property<string>("CuiName")
                        .HasColumnName("cui_name")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.HasKey("RestId", "CuiName");

                    b.HasIndex("CuiName");

                    b.ToTable("resturant_cuisin");

                    b.HasData(
                        new { RestId = 2, CuiName = "Korean" },
                        new { RestId = 1, CuiName = "Chinese" },
                        new { RestId = 4, CuiName = "Malaysian" },
                        new { RestId = 3, CuiName = "Canadian" },
                        new { RestId = 5, CuiName = "Chinese" },
                        new { RestId = 2, CuiName = "Chinese" }
                    );
                });

            modelBuilder.Entity("WebApplication1.Models.ResturantCuisin", b =>
                {
                    b.HasOne("WebApplication1.Models.Cuisin", "CuiNameNavigation")
                        .WithMany("ResturantCuisin")
                        .HasForeignKey("CuiName")
                        .HasConstraintName("FK__resturant__cui_n__534D60F1");

                    b.HasOne("WebApplication1.Models.Resturant", "Rest")
                        .WithMany("ResturantCuisin")
                        .HasForeignKey("RestId")
                        .HasConstraintName("FK__resturant__rest___52593CB8");
                });
#pragma warning restore 612, 618
        }
    }
}
